// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// // import "../globals.css";

// const inter = Inter({ subsets: ["latin"] });
// import AuthProvider from "@/context/AuthProvider";
// import Navbar from "@/components/Navbar";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <Navbar/>
//       <body className={inter.className}>{children}</body>

    
//     </html>
//   );
// }

import Navbar from '@/components/Navbar';

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      {children}
    </div>
  );
}
